name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:
  test-latest:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, macos-15 ]
      fail-fast: false
    name: "Test latest ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download BSC
        id: download
        uses: ./
        with:
          os: ${{ matrix.os }}
          version: latest
          path: ../

      - name: Build
        run: |
          echo Version tag: ${{steps.download.outputs.tag}}
          echo Version hash: ${{steps.download.outputs.commit}}
          export PATH=$PWD/../bsc/bin:$PATH
          bsc -v

  test-release:
    strategy:
      matrix:
        version: [ 2024.01, 2024.07 ]
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, macos-15 ]
        exclude:
          # macOS 14 was introduced at 2024.07
          - version: 2024.01
            os: macos-14
          # macOS 15 has not been introduced yet
          - os: macos-15
      fail-fast: false
    name: "Test release ${{ matrix.version }} ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download BSC
        id: download
        uses: ./
        with:
          os: ${{ matrix.os }}
          version: ${{ matrix.version }}
          path: ../

      - name: Build
        run: |
          echo Version tag: ${{steps.download.outputs.tag}}
          echo Version hahs: ${{steps.download.outputs.commit}}
          export PATH=$PWD/../bsc/bin:$PATH
          bsc -v
